OPENAI_API_KEY = ""
LLMONITOR_APP_ID = "dfbdd248-c0b7-468a-bc90-396137b9fae2"
PINECONE_API_KEY = "0cdf1bbc-c528-4859-b96d-1a1c3583b007"
PINECONE_ENV = "gcp_starter"
LANGFUSE_SECRET_KEY="sk-lf-74ef5030-28e1-4ae6-bbcb-b8194dfae5f2"
LANGFUSE_PUBLIC_KEY="pk-lf-dcaf0172-819f-46d1-843d-4b002973f35e"
LANGFUSE_HOST="https://cloud.langfuse.com"


APP_PASSWORD = "1639"